### PR TITLE
Bugfix/url filters

### LINKED ISSUE #253: Tests fail because of a date without time is used, do we need to support that?
Example test:
```rust
    assert_eq!(v!("2001-02-03"), filters!(escape, date(2001, 2, 3)));
```

### LINKED ISSUE #268: `url_decode` doesn't seem to be decoding correctly
Example test:
```rust
    assert_eq!(v!("foo bar"), filters!(url_decode, v!("foo+bar")));
```

### PR DESCRIPTION
**Pull request by or17191**
- [ ] Tests created for any new feature or regression tests for bugfixes.

This PR fixes #268.
It also attempts to fix #253, but I'm not sure if this is the correct fix. The behavior of the `url_{encode,decode}` filters relies on Ruby objects having a `.to_s` method.
If we want to fully emulate this for Date objects in rust, we must make `Date` a first class citizen in the `Value` enum. This would require us to rename the current `Date` object to `DateTime`, which I imagine will break all sorts of backwards compatibility.

What do you think we should do?

### CODE REVIEW

File: tests/conformance_ruby/standard_filter_test.rs [hunk 1]
```diff
@@ -120,14 +120,13 @@ fn test_escape_once() {
...
 #[test]
-#[should_panic] // liquid-rust#253
 fn test_url_encode() {
     assert_eq!(
         v!("foo%2B1%40example.com"),
         filters!(UrlEncode, v!("foo+1@example.com"))
     );
     assert_eq!(v!("1"), filters!(UrlEncode, v!(1)));
-    assert_eq!(v!("2001-02-03"), filters!(UrlEncode, date(2001, 2, 3)));
+    assert_eq!(v!("2001-02-03"), filters!(UrlEncode, date_string(2001, 2, 3)));
```
Comment (epage) [inline tests/conformance_ruby/standard_filter_test.rs]: I think I'd like to keep `date` for now.  Compatibility with liquid-rb will require us to add Date support.

(ditto for decode)

**Comment by epage** [comment]
Don't forget to run `cargo fmt --all` with your changes.  Looks like that is why the CI is failing.

File: tests/conformance_ruby/standard_filter_test.rs (hunk 1 above)
Comment (or17191) [reply tests/conformance_ruby/standard_filter_test.rs]: How do you want to add Date support? Since every place the repository refers to "Date" it means "DateTime", adding Date will require doing one of two "breaking" things:
- Rename the "Date" concept to "DateTime" and add a "Date" concept. The problem with this is that existing code will be legal but will function differently. The current filter architecture restricts this change, since it maps each parameter type to a single value type, so we can't have a "date" parameter type that starts as a "Date", and then falls back to "DateTime".
- Add a "DateOnly" concept to specify "Date" (vs "DateTime"), which is counter-intuitive.

Comment (epage) [reply tests/conformance_ruby/standard_filter_test.rs]: I'd go for renaming `Date` to `DateTime`.  We still have a relatively high-churn API and few users so I'm ok with breaking.

**Comment by epage** [comment]
Thanks for doing this!

**Comment by or17191** [comment]
I'm having some issues with adding `Date` support. I can't find an API that supports date only string parsing and timezones. `DateTime` doesn't support date only parsing, `Date` doesn't support string parsing at all, and `NaiveDate` doesn't support timezones. Which should I use?

**Comment by epage** [comment]
Does a `Date` need a timezone?  Seems like `NaiveDate` would work.
